### ISSUE TITLE
Wrong Server Class used for mORMot

### ISSUE THREAD

**Issue by synopse** [d-mozulyov/NetBenchmarks#1]
The mORMot sample uses SynCrtSock.THttpServer which is a socket-based server focusing on HTTP/1.0 non persistent connections behind a reverse proxy. It creates one thread per client, so it does not scale well above a few dozen connections.

On Windows, you should use THttpApiServer which is http.sys based so is reported to work as fast as TMS Sparkle.

Also, consider adding mORMot 2 THttpAsyncServer in your benchmark.
It is socket-based, but it is purely event driven, and designed to scale good with a lot of concurrent connection. It is slightly slower with 1 or 10 connections, because it was not focusing on this, but it scales almost linearly.

Last but not least, please consider benchmarking Linux Delphi/FPC servers.
This is what should be used on production. And in this respect, mORMot 2 THttpAsyncServer uses the epoll API which makes it very efficient.

**Comment by d-mozulyov** [comment]
Thanks a lot for your feedback!
Could you please send a Pull Request with corrections?
